### ISSUE TITLE
[Suggestion/Compatibility] Foot ball for salt tank

### ISSUE THREAD

**Issue by Omegathenotsofunnyman** [LegaSource/AddonFusion#2]
The title says it all, and considering footballs nature i think its pretty fair to assume she's spectral in nature
football form football https://thunderstore.io/c/lethal-company/p/Kittenji/Football/

**Comment by LegaSource** [comment]
Football is indeed a ghostly entity, but it doesn't function the same way
I haven't played with it, but it seems that it doesn't really enter a chase phase and only forces the player to perform actions
The salt tank addon adds a counter to the chase phase of DressGirl and Herobrine, I'm not sure if it could be effectively applied to this other entity

I'm not completely against it, though; I'll wait to see your feedback
Since I don't play this mod, I'm not very familiar with it

**Comment by Omegathenotsofunnyman** [comment]
Only reason i bring this up is due to her acting extremely similarly to the ghost girl, to the point of once seeing football i just act as if I'm haunted. 
code wise, idk if she actually has a chase phase but gameplay wise it feels as if she does.

from my experience shes just ghost girl with less sound cues she still:

 * stalks the player only apearing offscreen
 * chases you down for a certain amount of time until disapearing
* and causes something upon contact (the mini game which kills you if you fail)

like i said idk about code wise, but she feels like she definitely has one (sorry if i could provide any more details)

**Comment by LegaSource** [comment]
I've added the ability to counter the Football entity during its chase phase in the v1.0.5
